#5.a)
nombre= ( input("Ingrese su nombre:"))
apellido=(input("Ingrese su apellido:"))
edad=(input("Ingrese su edad:"))
print(nombre)
print(apellido)
print(edad)
#5.b)
nombre= ( input("Ingrese su nombre:"))
apellido=(input("Ingrese su apellido:"))
edad=(input("Ingrese su edad:"))