print("Néstor", "Cortez", "16", "años",sep='_')
print("\tcalle", "\tnumero","\tcodigo postal")
print("\ncalle", "\nnumero", "\ncodigo postal")
print("Feliz", "\n\t\tPrimavera","\n\t\t\t\t\t2024")
print("Solo podemos ver poco del futuro,")
print("pero lo suficiente para darnos cuenta de que hay mucho que hacer")
print("        *")
print("       * *")
print("      *   *")
print("     *     *")
print("    ***   ***")
print("      *   *")
print("      *   *")
print("      *****")